# Generated by Django 4.2.4 on 2023-08-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_alter_photo_approved_alter_photo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='app.tag')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.childcategory'),
        ),
    ]
