# Generated by Django 4.2.4 on 2023-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairmans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chairmans_images/')),
                ('bio', models.TextField(blank=True)),
                ('year_started', models.PositiveIntegerField(blank=True, null=True)),
                ('year_ended', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
