# Generated by Django 4.2.4 on 2023-08-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chairmans_alter_childcategory_tags_alter_photo_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chairmans',
            new_name='Chairman',
        ),
    ]
