# Generated by Django 4.2.4 on 2023-08-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_chairmans_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='video_parts/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app.video')),
            ],
            options={
                'unique_together': {('video', 'part_number')},
            },
        ),
    ]
