# Generated by Django 4.2.4 on 2023-08-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_video_videopart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopart',
            name='title',
        ),
    ]
