# Generated by Django 4.2.4 on 2023-08-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_pdfbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
