# Generated by Django 4.2.4 on 2023-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_videopart_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
